frontend/backend: modify transaction loading flow and add fiat value at time of transaction
Beerosagos/bitbox-wallet-app pull request #1
Opened 2022-06-30 09:49 UTC by Beerosagos

/transactions endpoint modified to load only data displayed in transactionfrontend list

A new /transaction endpoint created to load all available data for specific transactionin order to populate the detailed transaction view in frontend

FiatConversion component modified to use backend-calculated fiat amount conversionswhen available

Added code to show fiat value at time of transaction in detailed transaction view

2022-06-30 09:56 UTC, Beerosagos commented
I am not sure about how to handle localization, so I started adding locales for IT and EN. Is that ok?

2022-06-30 10:17 UTC, Beerosagos commented
One more thing: I only tested with TBTC for now, but I think it would be better to test also in ETH, if possible.

2022-06-30 12:32 UTC, thisconnect commented
add new keys to EN, I am not sure if IT will be imported

existing keys need to be changed in locize and then pulled in a different PR

2022-07-04 14:18 UTC, thisconnect requested changes
Nice @Beerosagos 👍 

Left some comments, I think there is an issue with live updating. I'll do some testing on master.

also squash the 2 commits into 1?

2022-07-04 14:18 UTC, thisconnect commented on frontends/web/src/components/transactions/transaction.tsx
> +    })
please add semicolon; (I should configure the linter that semicolons are required)

2022-07-04 14:18 UTC, thisconnect commented on frontends/web/src/components/rates/rates.tsx
>  }
There is already an `IAmount` interface with the same fields in `api/account.ts`, but conversions is not optional… I did a quick test and made it optional and TypeScript did not complain, maybe use the one from `api/account.ts` and make it optional? 

https://github.com/digitalbitbox/bitbox-wallet-app/blob/197c8b7d4113d71bf717d391a70eda3b5f9b4cac/frontends/web/src/api/account.ts#L135-L139

2022-07-04 14:18 UTC, thisconnect commented on frontends/web/src/components/rates/rates.tsx
> +      formattedValue = formatCurrency(rates[coin][active] * Number(amount.amount), active);
I believe you mentioned that this is only used in the send view is that correct? maybe add a comment?

2022-07-04 14:18 UTC, thisconnect commented on frontends/web/src/components/transactions/transaction.tsx
> -      weight,
nice 👍 , much cleaner with `transactionInfo`, just one note, those props were able to live update ( data passed  from `account.ts`) whereas now the data is loaded once, on `showDetails`. Most of the fields don't change but I believe some do, i.e. numConfirmations. I make a comment on that line...

2022-07-04 14:18 UTC, thisconnect commented on frontends/web/src/components/transactions/transaction.tsx
> +                <p>{transactionInfo.numConfirmations}</p>
If I am not missing something I believe `numConfirmations` did live update (data passed through the components from `account.tsx`). I would keep using `numConfirmations`  from props so it still can update once there is a new block.

2022-07-05 09:11 UTC, Beerosagos commented on frontends/web/src/components/rates/rates.tsx
> +      formattedValue = formatCurrency(rates[coin][active] * Number(amount.amount), active);
I made a deeper check. It seems to me that it is used in sending (https://github.com/Beerosagos/bitbox-wallet-app/blob/07ee89f61397c26f34cd7877dacf6592c2acf7b3/frontends/web/src/routes/account/send/utxos.tsx#L108) but also in the account summary (https://github.com/Beerosagos/bitbox-wallet-app/blob/07ee89f61397c26f34cd7877dacf6592c2acf7b3/frontends/web/src/routes/account/summary/accountssummary.tsx#L262).
If I am correct, maybe we could make a dedicated issue for the account summary, to get fiat amount already converted by backend?

2022-07-05 09:16 UTC, thisconnect commented on frontends/web/src/components/rates/rates.tsx
> +      formattedValue = formatCurrency(rates[coin][active] * Number(amount.amount), active);
ack, yes a separate issue/PR makes sense.

2022-07-05 13:49 UTC, Beerosagos commented on frontends/web/src/components/rates/rates.tsx
> +      formattedValue = formatCurrency(rates[coin][active] * Number(amount.amount), active);
UPDATE: after further checks I think that the only point where the conversion is done by the frontend is in the account summary, where it computes the total fiat balance of several accounts of the same coin. 
https://github.com/Beerosagos/bitbox-wallet-app/blob/07ee89f61397c26f34cd7877dacf6592c2acf7b3/frontends/web/src/routes/account/summary/accountssummary.tsx#L262

Could be probably fixed with a call to `coins/convertToFiat` like in: https://github.com/Beerosagos/bitbox-wallet-app/blob/07ee89f61397c26f34cd7877dacf6592c2acf7b3/frontends/web/src/routes/account/send/send.tsx#L395

I'll make a dedicated issue.

2022-07-05 14:49 UTC, Beerosagos commented on frontends/web/src/components/transactions/transaction.tsx
> +    })
Done!

2022-07-05 14:50 UTC, Beerosagos commented on frontends/web/src/components/rates/rates.tsx
>  }
Good point! making it optional doesn't seem to rise any issue. Done.

2022-07-05 14:51 UTC, Beerosagos commented on frontends/web/src/components/transactions/transaction.tsx
> -      weight,
You are right, fixed it! Thx.

2022-07-05 14:51 UTC, Beerosagos commented on frontends/web/src/components/transactions/transaction.tsx
> +                <p>{transactionInfo.numConfirmations}</p>
You are right, fixed it! Thx.

2022-07-05 15:03 UTC, Beerosagos commented
Thanks for the review! Now should be better.

While testing again I noticed a small bug: when I create a new transaction, the historical fiat value won't be available until the next rates update, but it is not a field meant for live updating. This means that it won't be displayed until I open the transaction detail again. 
If this is acceptable (and my new commit is fine) I can squash the commits a make a new PR upstream, otherwise I can include that value to those loaded by the /transactions endpoint and have it updated too. 
wdyt?

2022-07-05 16:08 UTC, thisconnect commented
so the options are:
- show currently amount
- show placeholder "N/A" or dashes
- conditionally render the row only if the historical amount is available

I slightly prefer to only render the row if there is a historical value.

2022-07-06 06:20 UTC, Beerosagos commented
> 
It currently works as in your second option: when the historical value is not available there are dashes instead. But should be easy to render the row only if the value is available.

2022-07-06 07:03 UTC, thisconnect commented
@jadzeidan WDYT should be displayed if the historical value is not available right after a new TX was made (or if it happens for any other reason)?

2022-07-06 13:37 UTC, Beerosagos commented
Pushed a new commit to hide historical fiat value for unconfirmed transactions.

2022-07-06 14:34 UTC, thisconnect commented
LGTM, time to squash and open a PR on the main repo for marko to review?

2022-07-07 08:04 UTC, Beerosagos commented
upstream PR created: https://github.com/digitalbitbox/bitbox-wallet-app/pull/1724

Closing this PR

2022-07-07 08:04 UTC, closed without merging