frontend: updates chart data is older than expected message
Beerosagos/bitbox-wallet-app pull request #2
Opened 2023-03-23 13:32 UTC by thisconnect

Show which coins are not up-to-date, but hide fiat as on account summary only 1 fiat is used.

Show time-ago of the coin with the oldest conversion rate, so that user understand that the chart is a bit off.

Use Intl.RelativeTimeFormat api, which is relatively new but should be supported in chrome since v71.

cc @benma

2023-03-23 13:33 UTC, thisconnect commented on frontends/web/src/routes/account/summary/chart.tsx
> +        : outdatedCoins[0].toUpperCase();
added a comment before variable declaration, as this is a bit a weird construct.

2023-03-23 13:34 UTC, thisconnect commented on frontends/web/src/routes/account/summary/chart.tsx
> +  private relativeTime = new Intl.RelativeTimeFormat(this.props.i18n.language, { style: 'long' });
`Intl.RelativeTimeFormat` is relatively new, but pretty cool IMO.

2023-03-23 13:35 UTC, thisconnect commented
![Screen Shot 2023-03-23 at 14 19 12](https://user-images.githubusercontent.com/546900/227220408-f2dd0c51-a040-4e64-8026-576d9b6a9707.png)

![Screen Shot 2023-03-23 at 14 20 41](https://user-images.githubusercontent.com/546900/227220483-0aea27ec-337c-4e32-84d2-edb78bbd606f.png)

2023-03-23 13:40 UTC, thisconnect commented
ok this is as far as I got, I didn't test this in qt nor with tokens.

please feel free to squash into your branch/commit, if you guys like it

cc @Beerosagos @benma

2023-03-23 16:11 UTC, Beerosagos requested changes
Amazing, thanks! Just pointed out a couple nits

2023-03-23 16:11 UTC, Beerosagos commented on frontends/web/src/routes/account/summary/chart.tsx
> +  private relativeTime = new Intl.RelativeTimeFormat(this.props.i18n.language, { style: 'long' });
pretty cool indeed!

2023-03-23 16:11 UTC, Beerosagos commented on frontends/web/src/routes/account/summary/chart.tsx
> +    if (!outdatedCoins.length) {
I'd remove this check. Rates in `ratesTimestamps` are only there if they're out of date.

2023-03-23 16:11 UTC, Beerosagos commented on frontends/web/src/routes/account/summary/chart.tsx
> +        : outdatedCoins[0].toUpperCase();
Amazing!

2023-03-23 16:11 UTC, Beerosagos commented on frontends/web/src/locales/en/app.json
> +    "dataOldTimestamps_one": "Exchange rates for {{name}} is older than expected. Last updated {{timeAgo}}",
I'd simplify removing this option: since the subject is the rates it is correct always to use the plural form, I think.

2023-03-27 07:06 UTC, thisconnect commented on frontends/web/src/locales/en/app.json
> +    "dataOldTimestamps_one": "Exchange rates for {{name}} is older than expected. Last updated {{timeAgo}}",
does that mean if USD/ETH is out-of-date then USD/BTC is also always out-of-date ?

can't it happend that only 1 pair is out-of-date? what if the user only has 1 coin?

2023-03-27 07:06 UTC, thisconnect commented
I noticed I missed removing importing a type.

![Screen Shot 2023-03-27 at 09 06 37](https://user-images.githubusercontent.com/546900/227865838-7cd54b1f-1078-4f0d-90a2-4f82dc42cb0b.png)

2023-03-27 07:17 UTC, thisconnect commented on frontends/web/src/routes/account/summary/chart.tsx
> +    if (!outdatedCoins.length) {
ah, but I think the filter  `.filter(coin => ratesTimestamps[coin as CoinCode] < twoHoursAgo)` is still needed to see wihch pair exactly is out of date, do you agree?

2023-03-27 07:23 UTC, Beerosagos commented on frontends/web/src/locales/en/app.json
> +    "dataOldTimestamps_one": "Exchange rates for {{name}} is older than expected. Last updated {{timeAgo}}",
In that case would be smth like ''Exchange rates for BTC are older than expected. Last updated ...". That is correct since "rates" is plural anyway

2023-03-27 09:33 UTC, Beerosagos commented on frontends/web/src/routes/account/summary/chart.tsx
> +    if (!outdatedCoins.length) {
Sorry, you're right. I misremembered the fact that up-to-date rates were already filtered out in the backend

2023-03-27 09:33 UTC, Beerosagos approved these changes
Thanks! I'll merge and squash with a couple changes in my branch

2023-03-28 07:28 UTC, Beerosagos commented
Squashed in https://github.com/digitalbitbox/bitbox-wallet-app/pull/1993/commits/6b8df75b3be7f497b60f60352e885d9665799978 Thanks @thisconnect :pray:

2023-03-28 07:28 UTC, closed without merging